* Antaŭparolo

<!--Plibeligo / korekto; ĝueblo; sennaciigo;
KANDİD, (Baron’un kızı) Matmazel Künegond - Fräulein Kunigunde; Pokokürante

>  Voltaire. Kandid Ya da İyimserlik Üstüne. Çev.Server Tanilli. Say Yayınları. s.149. 
> (Вольтер О Кандиде или Оптимизме. Транс.Сервер Танилли.)
> Publisher: SAY PUBLICATIONS
> Publication Year: 1984
> Translator: SERVER TANILLI
> Publication Place: ISTANBUL
> Tongue: Turkish
https://www.mersintime.com/kandid-ya-da-iyimserlik-ustune-makale,1008.html

eraroj Lantiaj indikas evoluon de la Franca lingvo;
bildoj

Ja kiel edikitino de Franca pesiono en Berlino povis memori germanan nomon, aŭ se ŝi ja memoris, aprezi ĝin?
 -->

https://flibusta.club/b/624065/read

** A. Pope

Lorsque l'illustre Pope donna son /Essai sur l'Homme/, et qu'il
développa dans ses vers immortels les systèmes de Leibnitz, du lord
Shaftesbury, et du lord Bolingbroke, une foule de théologiens de
toutes les communions attaqua ce système. On se révoltait contre cet
axiome nouveau que /tout est bien/, que /l'homme jouit de la seule mesure
du bonheur dont son être soit susceptible/, etc.
«Poème sur le désastre de Lisbonne» [ 1755 ] (Préface)
https://artflsrv03.uchicago.edu/philologic4/toutvoltaire/navigate/522/1/2/?byte=7368

[9] Tio estas misprezento de la penso de Lejbnico. Plej bona ano de limigita aro ne nepre estas tre bona. «La plej bona el ĉiuj eblaj mondoj» ne nepre estas perfekte bona. Eĉ male, laŭ Lejbnico ĉiuj eblaj mondoj estas neperfektaj, kaj en tio konsistas la <em>metafizika malbono.</em> Laŭ Lejbnico, «malplia malbono estas speco de bono» (<i lang="fr">un moindre mal est une espèce de bien</i>), tial ankaŭ eblus paroli pri «la malplej malbona el la eblaj mondoj» (kvankam matematike tio ne nepre estas egala).<br />
Fakte ĉi tie okazas konfuzo de la teodiceo de Lejbnico kun la
optimismo de Angla skolo, esprimita en la filozofia poemo «Eseo pri
Homo» fare de Aleksandro Popo (kiu verkadis ne malpli plaĉe ol lia
amiko Voltero):

** Kiom eble plej

*Kiom*, antaŭ *eble*, ne havas la saman signifon, kiel la paralela *kiel*: per
*kiel eble plej* oni esprimas la plej altan gradon de superlativo: /venu kiel
eble plej rapide/ signifas: venu kun la maksimuma rapideco. Male *kiom
eble* havas la nuancon de limigo: /venu kiom eble rapide/ signifas: venu
rapide, sed nur tiel rapide, kiel vi povas. Kp.: /Ĉiuj uzu la novajn vortojn
kiom eble egale[Z]; ni decidis kiom eble ĉion fari mem[Z]/. Kp. ¶261.
[PAG §88, p. 121]



Ainsi dans Candide, Voltaire critique l’optimisme de Leibniz et va le pousser au ridicule à travers le personnage de Pangloss, grand philosophe, professeur de "métaphysico-théologo-cosmolonigologie" et précepteur de Candide. La philosophie de Pangloss peut se résumer en cette phrase "Tout est au mieux dans le meilleur des mondes possibles" et est une critique virulente de Voltaire contre la thèse leibnizienne du meilleur des mondes. Ainsi, Voltaire déforme la pensée de Leibniz, qui n’affirme pas que le monde est parfait et sans souffrance, mais simplement qu’en dépit des souffrances présentes dans notre monde réel, ce dernier est le meilleur qui soit.
https://www.rtbf.be/article/leibniz-et-sa-theorie-du-meilleur-des-mondes-possibles-10684612

Kp "Tout va pour le mieux dans le meilleur des mondes"
Tout est/va au mieux. Le temps est ici superbe (...). Je me porte fort
bien, et tout va au mieux (Napoléon Ier, Lettres Joséph., 1806,
p.110).

− Proverbes
♦ Gén. p. iron. Tout est pour le mieux dans le meilleur des mondes: Tout va très bien.
https://www.cnrtl.fr/definition/meilleur

** Prudento
Eĉ se «prudento estas la plej malnobla el la virtoj» (A. Frans’), ĝi
tamen estas granda virto.
** Laŭvortismo

Перевод - «живой организм»: он воссоздает «органическую цельность»подлинника [2, с. 620]. В понятие «органической цельности» входят:
 1. полное тождество целого при отсутствии сходства между отдельными
    элементами: верная передача смысла, чувства, стиля, духа, красоты,
    изящества подлинника [1, с. 89];
 2. точное воспроизведение тематики [1, с. 61],
 3. языковые признаки, в том числе фонетика [1, с. 61],
 4. стилистические признаки: поэтическое очарование, своеобразие,
    прелесть подлинника, обаятельность формы [1, с. 61];
 5. воспроизведение динамики текста подлинника [1, с. 37];
 6. отсутствие буквализма: воспроизведение не «буквы - буквой»,
    «слова - словом», но «улыбки - улыбкой», «красоты - красотой»,
    «вдохновения - вдохновением», «музыки - музыкой» [1, с. 50, 61,
    76, 92]; 7) воссоздание интонаций, эмоций подлинника,
    афористичности [1, с. 61 - 62].

(Pli grave: necesas *kompreni* la celojn kaj signifojn.)
 
** Ilustraĵoj:
https://commons.wikimedia.org/wiki/Category:Candide?uselang=de

** Kosmopolitismo

Tandis que la France tourne les yeux vers l'Angleterre (mais aussi vers la Hollande, la Russie, la Prusse, la Chine, etc. dans le domaine des échanges intellectuels et artistiques), on peut aussi dire que l'Europe est " sans frontières " pour tout ce qui vient de la France :

" Au temps de Louis XIV, les princes, grands et petits avaient
commencé à construire des Versailles miniatures. . . . Au siècle
suivant, ce sont les livres, les tableaux, les costumes, les meubles
français qu'il est indispensable de faire venir : la langue française
est parlée dans toutes les cours. . . . Le prestige de la vie
parisienne est si grand, que les plus fortunés viennent se fixer dans
cette capitale où tous se sentent chez eux : Casanova dit déjà, à la
fin du siècle : 'On ne vit qu'à Paris, on végète ailleurs.' L'Europe
charmée par le cosmopolitisme parisien, par l'universalisme de la
pensée française, est, au siècle des lumières, l'Europe française. "

Georges Duby et Robert Mandrou, Histoire de la civilisation française, 2 vols. (Paris : Armand Colin, 1984), 2 :132, 125.
https://chalk.richmond.edu/mlccontextes/18_siecle/files/cosmopolite.htm

Sekve, reverkisto devas anstataŭigi la hejmigon per Francigo per hejmigo cellingva. Tiurilate la plej evidenta kaj la plej ŝoka decido en mia prilaboraĵo estas la anstataŭigo de leŭgoj kaj mejloj per kilometroj.

** Internaciismo
The group around Candide form neither a state nor even family. They
are at most a tiny enclave in a world given over to evil; a refuge, a
place o asylum (as they said at the time) for a group of cripples whom
chance and misfortune have| brought together. None of the farm’s
residents is a native of the place; they reconstitute a miniature
homeland in a place where they can lead a better life—and they can
lead a better life when they are not dependent on either religious or
political power. It’s important to note that the group of exiles is
cosmopolitan: in addition to the Westphalians (Candide, Cunégonde,
Pangloss, Paquette), there are the Italians (the old woman, brother
Giroflée), a Dutchman, more or less (Martin), and the Metis Cacambo.
This group would come close to being a symbol of all humanity, were it
not for the individual nuances of skin color and opinion that Voltaire
holds precious and that he will always want to preserve in all his
calls for toleration. The group is marginal, so small that it can
dispense with the problem of political organisation. Voltaire’s
evocation of productive labor checks any thoughts of utopia. This
small society is in no way a model. “The small farm yielded a great
deal.” That is all. It’s very little, some will say. Voltaire does not
need more. (As for Rousseau, he offers}

 

 



** Kunegundo
 Cunigunde of Luxembourg
 (http://en.wikipedia.org/wiki/Cunigunde_of_Luxemburg), a Princess
 accused of being unchaste who proved her innocence by walking on
 flaming irons without injury!
  in Latin, Cunegundis [Martyrologium Romanum, 3 March, #8 (2005)] or Kinigundis
There are two versions in Latin for Kunegunda: Cunegundis, is (a Third
 Declension noun) and Cunegunda, ae (a First Declension noun). The
 first version of the name employs Third Declension endings for the
 various cases and the second version uses First Declension endings.
https://forum.polishorigins.com/viewtopic.php?p=35610&sid=0dae47f34b5918cca3880dd4d0c881fe

Freifräulein n баронесса (дочь барона) (2-foje en G20).

* Vortordo

<p>La sama kutimo estas propra al la simile fiksakcenta lingvo pola.</p>

[Ĉap. 5ª]
Chce się rzucić za nim w morze
Li volas sin ĵeti en la maron

[Ĉap. 12ª]
sto razy chciałam się zabić
centfoje mi volis min mortigi,

[Ĉap. 19ª]
Człowiek, do którego się zwrócili, był ...
<!--Тот, к кому они обратились, оказался-->
La homo, al kiu ili sin turnis, estis ...

<p>Lanti’ konservas komplikaĵojn de <em>il y a</em>:</p>
<blockquote>
<p lang="fr"><strong>V:</strong> que dans quelques pays <em>il y ait des singes qui</em> obtiennent les bonnes grâces des dames</p>
<p><strong>L:</strong> ke en kelkaj landoj estas simioj, kiuj akiras favoron de virinoj</p>
<p><strong>S:</strong> ke estas landoj kie favoron de virinoj akiras simioj [ĉap. 16ª].</p>
</blockquote>
<blockquote>
<p lang="fr"><strong>V:</strong> Cunégonde lui parut ce qu’il avait jamais vu de plus beau.</p>
<p><strong>S:</strong> Kunegundo ŝajnis al li la plej bela el ĉiuj, kiujn li iam ajn vidis.</p>
<p>(<strong>L:</strong> Kunegond ŝajnis al li esti tio, kion li vidis plej bela.)</p>
</blockquote>

** Pasivo

V: vous qui fûtes tué par les Bulgares!
L: vi, kiu estis mortigita de la Bulgaroj!
S: Vi, kiun mortigis la Bulgaroj! [Ĉap. 14ª]

* La artikolo
** La nedifina
V: 9. Ce qui advint de Cunégonde, de Candide, du grand-inquisiteur, et *d'un Juif.*
L: 9. Kio okazis kun Kunegond, kun Kandid, kun la ĉefinkvizitoro kaj *kun judo*
A: 9. What Happened to Cunegund, Candide, the Grand Inquisitor, and *the Jew*
D: 9. Was sich mit Kunegunden, Kandiden, dem Grosinquisitor und *einem Juden* zuträgt
S: 9. Kio trafis Kunegundon, Kandidon, la ĉefinkvizitoron kaj *la Judon*

Kiel oni perceptu la nedifinitecon de "Judo"? Kial ne kiel enkonduko0n
de ankoraŭ unu, alia, nova persono?

Probable la artikolo estas ĝeneraliga: jen la sorto de ĉefinkvizitoro,
kaj jen la sorto de judo:

V: on enterre *monseigneur* dans une belle église, on jette *Issachar* à la voirie.
S: *La inkvizitoron* oni entombigas en bela preĝejo, *Isaĥaron* oni ĵetas en la rubejon.

Sed tiam devas esti egala nedifiniteco, kiel en la intera frazo de de
la sama ĉapitro:

V: Comment avez-vous fait ... pour tuer en deux minutes *un Juif* et *un prélat*? 
S: Sed kiel povis vi ... en du minutoj mortigi Judon kaj prelaton?

“The Prince and the Pauper”

----
V: j'avais la tête remplie du massacre ... et surtout du baiser que je
   vous avais donné derrière *un paravent*.
G24: und vor allem von dem Kusse, den ich Ihnen hinter *einem Wandschirm* an jenem Tage gegeben
A: and particularly the kiss I gave you behind *the screen*,
L: kaj ĉefe pri la kiso, kiun al vi mi donis *malantaŭ ekranego*
S: kaj precipe pri la kiso, kiun mi donis al vi malantaŭ *la faldoŝirmilo* [Ĉap. 8ª]
B: и особено за целувката, която ви дадох зад *паравана* в деня, когато
   ви видях за последен път.
----
16. La aventuro pri du junulinoj, du simioj, kaj +la+ indiĝenoj nomataj Oreleguloj
(kp en la Fabeloj:
ke ĉi tie troviĝas eksterordinare rimarkinda BIRDO, NOMATA najtingalo!
Proksime de Gudenaa, apud la arbaro de Silkeborg, simile al granda
remparo leviĝas ALTAĴO, NOMATA Aasen,)

Kp ankaŭ la piednoton de L pri "Eldorado" (ĉap. 17ª, la titolo):

L: Nomo, kiun la Eŭropanoj en la XVI-a jarcento donis al +iu+ fantazia
lando, kiun oni lokis ĉe la bordoj de +iu+ supozita lago Parimo,

(Se entute meti nedifinan pronomon, mi tie preferus ne ‹iu›n, sed
‹ia›n. ‹Iu› pensigas min pri elekto inter realaj objektoj.)

----
#+NAME: kelkaj
V: c'était pour voir si nous n'avions pas caché là quelques diamants
L: oni volis konstati ĉu ni ne kaŝis tie kelkajn diamantojn
B: за да видели дали не сме скрили там диаманти
S: tiel ili kontrolis, ĉu ni kaŝis tie juvelojn [ĉap. 11ª]

** La difina

Ĉap. 11ª
V: Je suis *la fille* du pape Urbain X et de la princesse de ...
G24: Ich bin *die Tochter* des Papstes Urban des Zehnten ...
B: *Дъщеря* (ne "ДъщеряTA"!) съм на папа Урбан X и на принцеса Палестрина.

Tamen simile [Ĉap. 1ª] ("filo" kaj la? filino):

V: Les anciens domestiques de la maison soupçonnaient qu'il était /fils/
de *la sœur* de M. le baron, et *d'un* bon et honnête gentilhomme du
voisinage
L: La malnovaj servistoj suspektis, ke lia patrino estas *la fratino* de
lia barona moŝto kaj lia patro *iu nobelo* el la ĉirkaŭaĵo
B: Старите слуги в дома подозираха, че е /син/ на *сестрата* на господин
барона и на *един добър и почтен благородник* от околността
G24: Die alten Diener des Hauses munkelten, er sei /das Kind/ *einer
Schwester* des Herrn Barons und eines guten braven Edelmannes aus der
Nachbarschaft ...
S: La malnovaj servistoj suspektis, ke li estas filo de fratino de lia
barona moŝto kaj de brava kaj bona nobelo najbara

Atentindas, ke /fils/ aperas senartikole, kontraste al /la fille/ en Ĉap. 11ª.

* Aspektoj
** Imperfekto
V: Pangloss était au milieu de sa phrase, quand Je familier fit un
signe de tête à son estafier qui lui /servait à boire/ du vin de Porto
ou d'Oporto. [Ĉap. 5ª]
L: Panglos estis ĉe la mezo de sia frazo, kiam la intimulo kapsignis al sia armita servistaĉo, kiu /donis/ al li por trinki vinon el Porto aŭ el Oporto.
S: Pangloso estis ĉe la mezo de la frazo, kiam la najbaro kapsignis al
sia armita servisto, kiu /estis verŝanta/ al li vinon nomatan «Porto»
aŭ «Oporto».

Ĉap. 10ª:
V:  On y /équipait/ une flotte, et on y /assemblait/ des troupes pour mettre à la raison …
L: Ĉi tie oni ekipis ŝiparon por milite prudentigi…
S: Tie estis ekipata ŝiparo kaj arigata trupo por prudentigi …

V: /j'inspirais/ déjà de l'amour; ma gorge /se formait/ [Ĉap. 11ª]
L: mi jam sentigis amon, mia brusto formiĝis;
S: mi jam inspiradis amon, mia brusto estis formiĝanta

V: Le soleil se couchait.
L: La suno malleviĝis.
S: La suno estis subiranta. [Ĉap. 16ª]

** ek + mensa verbo
<p>Pli ofte ol averaĝe ĉe la okcidentanoj Lanti’ esprimas inĥoativon (en la okcidentaj lingvoj inĥoativo de la mensaj verboj ial estas tabuita). Tio estas logika.</p>

L: Iun tagon la granda inkvizitoro ekvidis min cxe diservo [Ĉap. 8ª]

V: J'appris bientôt que 
L: Baldaux mi eksciis, ke [Ĉap. 11ª]

V: J'ai su que messieurs les religieux chevaliers de Malte n'y manquent jamais 
L: Mi eksciis, ke sinjoroj la religiuloj kavaliroj de Malta neniam
malatentas tiun kutimon,

V: dès qu'ils ont su que …
L: tuj kiam ili eksciis, ke …
S: de kiam ili eksciis ke … [Ĉap. 16ª]

V: On aperçut enfin les côtes de France.
L: Fine oni ekvidis la bordojn de Francio. [Ĉap. 21ª]

V: Les deux égarés entendirent quelques petits cris
L: La du erarvagantoj auxdis kelkajn krietojn
S: … la du vagantoj ekaŭdis krietojn, [Ĉap. 16ª]

<!--p>Sed iam redunda <emphasis>-ad</emphasis> ĉe daŭrverboj:</p>
<cite>
  <p><strong>V:</strong> il pleura longtemps;</p>
  <p><strong>L:</strong> li longe ploradis [Ĉap. 19ª]</p>
</cite-->


* Nomoj
Mi forigis la francan nobelan partikulon /de/ (kiu cetere ĉe la
germanaj nobeloj estus /von/).

** Candidus (cognomen), a third name of a citizen of ancient Rome

<p>Voltero evidente malŝatis la Germanan lingvon, kaj tion atestas du lokmomoj, per kiuj li parodias sian impreson pri la Germanaj sono kaj skribo. La parodioj estas pli malicaj ol spritaj aŭ trafaj; mi anstataŭigis ilin per formoj kiujn opinias pli amuzaj, aŭ almenaŭ kiuj kaŭzas al mi malplian vichonton (<em>Fremdscham</em>):</p>
<ul>
<li>Thunder-ten-tronckh → Tondro-tra-trunk’</li>
<li>Valdberghoff-trarbk-dikdorff → Valdberghof-dikdorf</li>
</ul>
<p>En la dua nomo mi forigis la negermanan troaĵon <em>trarbk.</em> Kurioze: Voltero duobligas la finajn foojn en <em>Hof</em> kaj <em>Dorf,</em> sed duonigas la komencan vuon de <em>Wald</em> ☺</p>
<p>La «esperantigo» de la unua nomo iom similas la «Nederlandan» nomon de la negocisto el ĉap. 19ª elpensian de Voltero: <i lang="nl">Vanderdendur,</i> kio france sonas proksime al <i lang="fr">vendeur [à la] dent dure</i> (t.e. «vendisto durdenta»). Lanti’ ŝanĝis tion al <i lang="nl">Vanderdentur;</i> en mia prilaboraĵo ĝi iĝis <em>Van-Durdent’</em>.</p>
https://openlibrary.org/publishers/Chez_Jean_van_Duren
https://www.amazon.com/Voltaire-Holland-1736-1745-Republique-Lettres/dp/9042923539

** Frato Levkojo

«Giroflé, girofla» : Jeu chanté
https://www.mamalisa.com/?t=fs&p=4523

** Paquette
la Germana traduko [G] ŝin rebaptas <i lang="de">Gertrude.</i> Mi
komprenas la motivon por tia ŝanĝo, sed al mi ĝi ne plaĉas (tro
arbitra; kaj min «Gertrudo» impresas malsame ol <i
lang="fr">Paquette</i>). Tamen la Lantia <em>Paket,</em> aŭ ĝia plua
asimilaĵo <em>Paketo</em> ĝenas en Esperanto (kaj en aliaj lingvoj
kiuj praktikas transskribon).</p>

La ĝena misasociaĵo <i lang="fr">Paquette—le paquet</i> france ne ekzistas (skribe <i lang="fr">-ette</i> sufiĉe diferencas de <i lang="fr">-et</i>; sone, ĉar en la komuna vorto <em>t</em> estas muta). La pola tradukisto trovis elegantan solvon: <em>Pakita</em> — sed en Esperanto ĝi la problemon ne solvas (ĉar aspektas kiel participo). <em>Panjo</em> kolizias kun la karesvorto por patrino. <em>Kanjo</em> estus bona solvo per si mem — sed la komenca *K* jam tro oftas en la nomoj de la geprotagonistoj: *K*andido, *K*unegundo, *K*akambo… La delikatan orelon de Voltero ŝokas la multaj germanaj t-sonoj (kion li parodias per <em>Thunder-ten-tronckh</em>); sed ial li ne rimarkis, ke la abundo de la tusaj K-oj estas ne malpli ĝena.
Mi koncedas, ke ĝi estas iom pli romantika ol konvenas al la rolulino,
sed pli taŭgan mi ne trovis. Ĉiel ajn, tio min malpli ĝenas ol /Paketo/.

** Ralph, Oporto

12. Porto, or rather Oporto: They are one and the same Portuguese
    city - a moment of pedantry (and a late addition, not present in
    the manuscript) which reminds us that this is a tale being told by
    *the obscure German with the English name, Doctor Ralph.* [ĉap.
    5ª]
** Misaj nomoj hispanaj
- "urbeto Avaseno (Avasena)" probable estas plumeraro de Voltero aŭ
  eble mislegita «Aracena». [ĉap. 9]
- Chillas [ĉap. 10] -- ??

*** don Fernando d'Ibaraa, y Figueora, y Mascarenes,y Lampourdos, y Souza.
L: Don Fernando de Ibaran, kaj Figuerora, kaj Maskarenes, kaj Lampurdos, kaj Suza
ES: señor don Fernando de IbarRa Figueroa Mascareñas Lampurdos y Souza
http://www.intratext.com/IXT/ESL0891/_PR.HTM

- Ibarra: Иба́рра (баск. Ibarra, исп. Ibarra) — баскская фамилия и топоним
- Figueroa (Galician: Figueiroa) is a Spanish surname of Galician origin.
- Mascareñas: фр. Mascareignes, порт. Ilhas Mascarenhas) — архипелаг в
  Индийском океане, расположенный в 650 км восточнее Мадагаскара.
  Острова названы в честь выдающегося португальского мореплавателя и
  политического деятеля XVI века Педру ди Машкареньяша (порт. Pedro de
  Mascarenhas).  Остров Реюньон является заморским департаментом
  Франции, остальные острова составляют государство Маврикий, входящее
  в британское Содружество наций.
- Грек Лампурдос подлец ... (Щедрин)
  http://rulibs.com/ru_zar/prose_rus_classic/saltyikov-schedrin/1q/j64.html
- Со́уза (порт. Sousa, в старой сохранившейся в Бразилии орфографии
  порт. Souza, португальское произношение: [ˈso(w)zɐ]) — португальская
  фамилия топонимического происхождения. Связана с названием реки
  Соуза[pt] на севере Португалии. Первый представитель рода Соуза и
  носитель фамилии родился в 1035 году. Часто употребляется с
  предлогом, указывающим на происхождение из определённой местности:
  de Sousa или в архаичной форме D’Souza. Соответствует испанской
  фамилии Соcа (исп. Sosa или исп. Soza).

Fernando=Hernán Cortés + de Monroy y Pizarro + Altamirano
Cortés byl synem Martína Cortése de Monroy a Doñi Cataliny Pizarro Altamarinové.
«семьи Кортесов, Монроев, Писарро и Альтамирано»
«Мартин Кортес де Монрой (1449—1528), отец Эрнана»
Фернандо, Эрнандо и Эрнан были в то время одним и тем же именем, для
которого в орфографии того времени существовало три разных написания
(Fernando, Hernando и Hernán), поэтому они в равной степени
использовались современниками.

His father, Martín Cortés de Monroy, born in 1449
to Rodrigo or Ruy Fernández de Monroy and his wife María Cortés,
was an infantry captain of distinguished ancestry but slender means.
Hernán's mother was Catalína Pizarro Altamirano.

* Mezurunuoj
** Promeno
<p>La plej ofta mezurunuo (aperanta 10-foje) estas *leŭgo* (Fr <emphasis>lieue</emphasis>). Unu el ties intuicie klaraj difinoj estas «la distanco kiun averaĝa viro piediras dum 1 horo», do 4–5 km. Laŭ NPIV, leŭgo estas «proksimume 4km». Laŭ la franca Vikipedio, la «Pariza leŭgo» en la tempo de la eldono de Kandido (1759) estis 3,248km = 10<sup>4</sup> da tiamaj francaj futoj (<emphasis>pieds</emphasis>).</p>
<p>Lanti’ tradukas la francan <emphasis>lieue</emphasis> per <emphasis>mejlo,</emphasis> probable ĉar leŭgo ankoraŭ ne ekzistis en Esperanto, tamen sen konverta rekalkulo: «deux lieues» → «du mejloj» [ĉap. 2ª]. Same faria la tradukistoj pola kaj rusa; kaj la germana „<a l:href="#http://www.zeno.org/Kategorien/T/Meyers-1905?fr=Lieue">Meyers Großes Konversations-Lexikon</a>“ (1905–1909) rekte asertas ke leŭgo estas «la franca mejlo, antaŭe diverslonga» (*Lieue* (spr. ljö), die französische Meile, früher in verschiedener Größe). Tio tamen estas malvera, kaj Voltero en du okazoj indikas distancon en mejloj.</p>
<p>Mi tamen koncedas, ke iam traduko per mejloj aspektas pli versimile. Ekz‑e [Ĉap. 2ª]:
<cite>
<p>Iun belan printempan tagon li decidis fari promenadon, kaj ekpaŝis rekte antaŭen … Apenaŭ li estis irinta <emphasis>du leŭgojn,</emphasis> kiam kvar aliaj herooj … lin kuratingas, ligas, kaj kondukas en karceron.</p>
</cite>
<p>Promeno 8-kilometra estas iom longa, sed ja imagebla. Strange impresas la adverbo: «<emphasis>apenaŭ</emphasis> li estis irinta 8km…». Post 


** Leŭgoj

je lui ai envoyé à deux mille cinq cents lieues d’ici un exprès dont j’attends la réponse [ĉap. 22]
kaj ke mi sendis al ŝi, je du mil kvincent mejloj for de ĉi tie, ekspresulon, kies respondon mi atendas.
Mi sendis al ŝi, de 2500 leŭgoj for de ĉi tie, ekspreson, kaj nun atendas respondon.
I have sent a messenger to her near two thousand leagues from here, and wait here for his return
Obecnie wysłałem do niej o dwa tysiące pięćset mil umyślnego posłańca i oczekuję jego powrotu.
я отправил к ней, за две тысячи пятьсот миль отсюда, посланца и теперь жду ее ответа.



La distanco Paramaribo (Surinamo) --- Parizo estas
2500 leŭgoj = 7191.30 km
(laŭ https://www.distancefromto.net/)
do, 1 leŭgo ≈ 2.88 km

La distanco Bonaero --- Parizo estas
11050 km; 11050/2500 ≈ 4.42 km

l'ancienne lieue de Paris (avant 1674) 10 000 pieds (futoj) =  3,248 km
La franca futo (ĝis 1799) estis 324,839 mm.

la lieue des Postes 	(1737-1793) 	2 200 toises 	=  4,288 km

On trouvait également une lieue de marche « extrêmement variable » ,
correspondant à une distance parcourue en une heure.

** Mejlo
★mejl/o 1 Mezurunuo de longo por teraj vojaĝoj: romia mejlo (1 472,5
m), angla mejlo (1 609,31 m); franca mejlo (7 422 m); germana mejlo
(7 500 m); sveda mejlo (10 000 m). ☞ kilometro.


** Futoj

Prusa:
6-й старый прусский пехотный полк (нем. Altpreußisches
Infanterieregiment No. 6) — прусский пехотный полк № 6, состоявший из
солдат выше среднего роста.

Минимальный рост солдат полка составлял 188 см = 6 preußische Fuß
kvin futojn kaj kvin colojn? = 5×12 + 5 = 65 coloj
188/65 ≈ 28,9mm > 27mm (franca colo)
https://ru.wikipedia.org/wiki/Потсдамские_великаны
Zoll 	Preußen 	1755 	0,026 154 5 m

** Eskudoj
<p>Krom tiajn ekzotajn monerojn Voltero volonte uzas «eskudojn» (France <i lang="fr">écu</i>), hejman moneron de siaj legantoj — eĉ en epizodoj Vestfalia (<a href="#talero02">ĉap. 2ª</a>) aŭ Turkia (<a href="#talero27">ĉap. 27ª</a>). En Esperanto tiu rolo de unueca hejma monero pli konvenas al <em>talero,</em> vorto oficialigita jam en la 1ª OA; cetere, «talero» pli konvenas ankaŭ situacie (talero ja efektive estis uzata en la menciitaj landoj), kaj internacie: ĝi estas la etimo de <i lang="en">dollar;</i> «piastro» estas alinome «hispana talero/dolaro» ktp.</p>

----
Franca eskudo en 1772: Écu dit “à la vieille tête” (29.26 g, 6h)
https://commons.wikimedia.org/wiki/File:Louis_XV_%C3%A9cu_1772_76001791.jpg?uselang=fr

$21.35 (je 2021-12-27)


* Principo de sufiĉa kialo, laŭ kiu

    nenia fakto povas okazi vera aŭ ekzistanta, nenia aserto — vera,
    se ne estas sufiĉa kialo pro kiu estas tiel kaj ne alie, kvankam
    tiujn kialojn plej ofte ni ne povas koni.

32. Kaj tiu de sufiĉa racio, laŭ kiu ni konsideras ke nenia fakto
    povas troviĝi vera aŭ ekzistanta, nenia elparolato vereca, se ne
    estas racio sufiĉa pro kiu tiele estas kaj ne alie, kvankam tiujn
    raciojn plej ofte ni ne povas koni.
----
* Leksiko
** labuś

** Anglio, Holando, Keĉuo
En A la vortoj /Britain, British/ neniam aperas.

** diamantoj / briliantoj
(cetere, V ofte uzas "diamanto" en la signifo "ajna juvelo"; ekz‑e
kiam temas pri "[[kelkaj]] diamantoj" en anuso)

----
ĉap. 1ª:

** gradoj da nobeleco
<span class="aside">[4] Temas la nombro de nobelaj geprauloj.
log<sub>2</sub>71 ≈ 6.15, t.e. la patro de Kandido estis nobelo en
almenaŭ la 7ª generacio. France <em>quartiers,</em> angle
<em>quarterings. — S.</em></span>

Sumo de geometria progresio:

b₁, b₂=q·b₁, ... b_n=q^{n-1}·b₁
S_n = b₁(qⁿ - 1) / (q - 1) = 2(2^{n-1} -1) / 1 = 2ⁿ - 2

2, 4, 8, ... 72

n=6: 64 -2 = 62
n=7: 126

2. Pangloss: See A Note on Names. In composing the character of Pangloss,
Voltaire may have been thinking of Leibniz’s disciple Christian Wolff (1679-
1754), and perhaps also of the French philosopher and writer Jean-Jacques
Rousseau (1712-78). In 1756 Voltaire had written an attack on Rousseau
entitled Lettre au docteur Jean-Jacques Pansophe (Letter to Doctor Jean-Jacques
Pansophe - ‘pansophe’ means ‘all-knowing)).

3. metaphysico-theologico-cosmo-nigology: Voltaire’s assault on cosmic optimism
is a compound-caricature of Leibniz, Pope and Wolff, the latter a rigidly
systematic thinker who introduced the word ‘cosmology’ to a wider world;
“nigology’ comes from nigaud (‘booby’).

4. no effect without cause: Leibniz: ‘Nothing ever happens without a cause or at
least a sufficient [determining] reason’ (Théodicée (1710), 1, 44; translated as
Essays in Theodicy on the Goodness of God, the Liberty of Man, and the Origin of
Evil), which Voltaire here reduces to tautology. Voltaire’s comedy habitually
separates cause and effect.

5. all is for the best: The passage is a burlesque reductio of the principle of final
causes, or the argument from design. Voltaire accepted a moderate form of
the principle, but attacked extreme materialist versions of it. Cf. his article
on ‘Final Causes’ in the Philosophical Dictionary (transl. Theodore Besterman,
London, 1972, pp. 205-7). Philosophically, ‘all is for the best’ means that
each thing is justified by its purpose in the plan of Creation, but common
parlance turns the expression into abject enthusiasm for the world as it s.

6. sufficient reason: A Leibnizian term (referring to that quality, in each thing,
which explains and justifies its existence), satirically redirected here from
‘metaphysical to physical concerns. The volitions of God are ‘sufficient
reasons’ determined by our perception of the good. Leibniz intended his
principle as a criterion of truth in the sphere of the contingent, that is, of
experience. It suggests a rationally constructed universe and so is connected
with his Optimism. Voltaire judged the principle to be a case of obfuscation,
and reduces it to the simple notion of cause and effect.


----
ĉap. 2ª:
4. King of the Bulgars: The Abars and the Bulgars, whom Voltaire had
encountered while researching his Essai sur Uhistoire générale et sur les meeurs
et l'esprit de nations (Essay on General History and on the Manners and Spirit of the
Nations, 1756), were two barbarian nations who laid waste the Byzantine
empire in the eighth and ninth centuries. In the contemporary setting of the
Seven Years’ War (1756-63), the references to recruiting officers and to the
tallness of recruits suggest that the Bulgars represent the Prussians and the
Abars the French. Etymologically, ‘Bulgars’ also imputes homosexuality to
Frederick and his tall troops (‘bulgar’ - bougre, ‘bugger’).

5. your glory is assured: By accepting the King's money and toasting the King's
health, Candide has unwittingly signed up for military service.

6. ramrod: Used for pressing the charge down the muzzle of the gun. The
manoeuvres described by Voltaire were newly essential to success on the
field of battle in the eighteenth century; by increasing their speed and
synchronization, the Prussians increased their mobility as a fighting force
and reduced their losses. Voltaire had witnessed the militarization of the
Prussian army in Potsdam during his stay with Frederick (1750-53), and he
closely followed developments in military tactics, as evidenced in the
opening of the next chapter.

7. freedom of the will: Under Frederick’s influence Voltaire had abandoned the
doctrine of freedom of the will, which he had formerly defended (in his
Eléments de la philosophie de Newton (Elements of the Philosophy of Newton), 1740)
and would subsequently mock.

----
ĉap. 3ª:
leste: 4) уст. элега́нтный

CHAPTER 3
How Candide ran away from the Bulgars, and what became of him

1. a harmony such as was never heard in hell: An ironic reference to Leibniz’s
theory of pre-established harmony. The Seven Years’ War was being waged
during the composition and publication of Candide. According to the 1761
title-page, Doctor Ralph, purported author of Candide, perished in this same
war in 1759. Voltaire wrote to an English correspondent, George Keith, on 4
October 1759: ‘The present war is the most hellish that ever was fought.
Your Lordship saw formerly one battle a year at most; but nowadays the
earth is covered with blood and mangled carcasses almost every month. Let
the contented lunatics who say that “All that Is, Is Well” be confounded! "Tis
not so, indeed, with twenty provinces exhausted and three hundred
thousand men murdered. I wish your Lordship the peace of mind necessary
in this lasting hurricane of horror.”

2. scoundrels who were infesting its surface: Soldiers were commonly seen as
recruited from the dregs of the population.

3. First the cannon ... a few thousand more: Voltaire’s description follows the usual
sequence of eighteenth-century battles: artillery exchanges followed by
infantry, followed by hand-to-hand fighting with bayonets. He omits the
cavalry charge.

4. Te Deums: Hymns of thanksgiving in the Catholic liturgy, traditionally sung
after victories: ‘a ceremony established to encourage the people, whom it is
essential always to deceive’ (Voltaire, Le Siécle de Louis XIV (The Age of Louis
X1V), 1751). That the Te Deum was often sung simultaneously in both camps,
for propaganda purposes, had already been criticized as ludicrous by the
philosopher Pierre Bayle (1647-1706) in his Dictionnaire historique et critique
(Historical and Critical Dictionary, 1695-7), and is one of the commonplaces of
Voltaire’s anti-religious polemic.

5. international law: Theorists of international law, such as Hugo Grotius (1583-
1645), had tried to legalize what they could not proscribe: hence the
theoretical justification of pillage or slavery, for example, which outraged
Voltaire.

6. Here old men ... arms and legs: The description in this passage is faithful to
contemporary accounts of the realities of war: a synthesis rather than an
exaggeration. ‘None of the atrocities in Candide is invented’ (Jean
Starobinski, ‘Voltaire’s Double-Barrelled Musket’, in Blessings in Disguise
(california, 1993), p. 85).

7. dealt with it accordingly: In his manuscript Voltaire originally added the
sentence: ‘Virtually the entire province had been destroyed.”

8. He begged alms ... how to earn his living: Begging was prohibited in Holland, and
Voltaire was a supporter of such measures.

9. This orator: A Protestant pastor; after the Revocation of the Edict of Nantes
(1685), Holland became one of the centres of asylum for free-thinkers,
Protestants and proselytizers against Rome.

10. a chain of necessity: The Leibnizian principle that all phenomena are of
necessity linked to one another, though the satire here is anti-determinist
rather than specifically anti-Leibnizian.

11. Anti-Christ: A view maintained by orthodox Calvinists.

12. Anabaptist: A member of a sixteenth-century Protestant sect, widespread in
Holland and Westphalia. Anabaptists rejected infant baptism, maintaining
that only adults could choose Christianity. Having originally been unpopular
for their sanguinary and radical views on property and religious discipline,
they had settled down in the eighteenth century, becoming peaceful
burghers - industrious, altruistic, tolerant of other sects - and as such had
earned Voltaire’s approval.

13. two legs, no feathers and a soul: The Anabaptist adds a soul to this famously
‘minimal definition of man, coined - according to Aristotle - by one of the
philosophers of the Academy (whereupon Antisthenes, the Cynic, presented
him with a chicken).

----
V: Maître Pangloss me l'avait bien dit que /tout est au mieux/ dans ce monde
L: Majstro Panglos prave diris, ke /ĉio statas kiel eble plej bone/ en ĉi tiu mondo
A: my Master Pangloss told me truth when he said that everything was for the best in this world;
P: Dobrze powiadał mistrz Pangloss, że wszystko w świecie dzieje się najlepiej;
G20: »Meister Pangloß hat wahr gesprochen, als er sagte, daß in dieser Welt alles zum besten eingerichtet sei,
R: что все к лучшему в этом мире,
B: че всичко е най-добре на този свят,


POSSIBLE [Littré]:
...
*Au possible*, au dernier degré, extrêmement, beaucoup.
Le fils d'un marchand, ignorant et présomptueux au possible, arriva un jour en une compagnie où j'étais, , Francion, VI, p. 221.
Incommode et revêche au possible, HAMILT., Gramm. 8.
Ce premier ministre [Richelieu], soupçonneux au possible, allait à mon père sur les ombrages qu'il prenait, SAINT-SIMON, 6, 86.
Le grand pensionnaire Barnevelt, qui était du parti contraire à Gomar [sur la prédestination], eut la tête tranchée à l'âge de soixante-douze ans, le 13 mai 1619, pour avoir /contristé au possible/ l'Église de Dieu, *VOLT*., Pol. et lég. Sur la tolérance, si elle est dangereuse..

*Au mieux*, *tout au mieux*, loc. adv. Très bien.
"À table trouvant tout au mieux, Je crois qu'un ordre des cieux Tient en haleine la sagesse", Béranger, Deo gratias.



----
ĉap. 4ª:
V:
Mais de quelle maladie est-elle morte? ne serait-ce point de ...
Non, dit Pangloss, elle a été éventrée par des soldats bulgares, 
L:
— ... Pro kia malsano ŝi mortis? ...
— ... La Bulgaraj soldatoj distranĉis ŝian ventron ...
S:
— Ne, — diris Pangloso. — Al ŝi distranĉis la ventron la Bulgaraj soldatoj...

[11] the courts which seize ... creditors: In 1754 Voltaire lost 8,000
livres of income from the bankruptcy of the son of the famous banker
Samuel Bernard. in whose hands he had placed part of his fortune. In
1758 he tried to recover some of these losses. A bankrupt’s creditors
could normally hope to be compensated by division of the bankrupt’s
estate. but the law delayed the process by seizing all of the estate
in the first instance, from which it would then deduct costs.

----
ĉap. 5ª:

V: Dieu ne leur a donné ni canons de vingt-quatre, ni baïonnettes ...
S: Dio donis al ili nek sieĝajn pafilegojn, nek bajonetojn por sin interbuĉi
[26] Kanonoj pafantaj per 24-funtaj (11,7 kg) obusoj estis vaste uzataj en la 18ª jc.

Oni ne plu klasas pafilojn laŭ la maso de la obuso, de post la 19ª jc
oni mezuras kalibron (ĉi-okaze 152 mmm por Francia «canons de
vingt-quatre», aŭ 140 mm por Brituja “24-ponder”). Tial la modernan
leganton «24-funta kanono» pensigus pri kanono kiu pezas 14 funtojn
--- dum fakte tia kanono pezis 2½ tunojn (sen afusto).

----
ĉap. 6ª:
Post la tertremo detruinta LA(??) tri kvaronojn de Lisbono

In reality, no auto-da-fé took place in response to the Lisbon
disaster. Three autos-da-fé were held in Lisbon - on 8 October 1756,
28 September 1757, 27 August 1758 - but these were unconnected with
the earthquake, and there were no executions.
    

----
ĉap. 7ª:
Frottez-vous de __ pommade, mangez et dormez. 
Ŝmiru vin per pomado, manĝu kaj dormu.
Kial ne "per LA pomado"? Ĉu partitivo?

----
ĉap. 9ª:
ili trarajdas 30 mejlojn (223 km) senhalte

- чем быстрее скачет лошадь, тем скорее выдыхается. На максимальной
  скорости 60 км/ч лошадь может держать темп без ущерба для здоровья
  1 мин. , за 10 мин. ее загнать можно, на скорости 30-40 км/ч для этого
  понадобится пару часов, со скоростью 10-20 км/ч переменным аллюром
  тренированная лошадь может двигаться до 20 часов без перерыва.
- один день 160 км говорят так.
- Полк может двигаться беспрерывно 7-8 часов в сутки. Нормальный
  переход устанавливается в 50 км. Через каждые 2-3 дня движения
  устраивается дневка Максимум что конница может дать с полным
  напряжением сил конского состава - это два марша подряд по 100 км
https://otvet.mail.ru/question/65046168


----
ĉap. 10ª:
3. Benedictine prior: The Benedictines were thought to be very wealthy.

4. Lucena... Chillas ... Lebrija ... Cadiz: The names are real, but the itinerary is
fantastical. Cadiz was the centre of trade with Spanish America. Voltaire
invested heavily in this trade. In 1756 he had invested part of his capital in
the fitting-out of a ship to transport Spanish troops from Cadiz, to quell a
Paraguayan Indian uprising, supposedly backed by the Jesuits (the ship was
named the /Pascal/, after their Jansenist enemy). Candide, Cunégonde and the
old woman embark on a ship effectively owned by Voltaire.

5. San Sacramento: Eighteenth-century Paraguay covered a far greater area
than today, much of it controlled by Jesuit missions. In 1750 the Spanish
government ceded the town of San Sacramento - situated inside the mission
settlements - to Portugal; the Indians rebelled against the prospect of
passing under Portuguese rule, and the Jesuits were held responsible (in
Voltaire’s manuscript, ‘who were accused of having incited reads: ‘who had
incited’). In 1755 Spain and Portugal sent an expedition to repress the
uprising, and guerilla activity continued for several years; Candide becomes
- briefly - a commanding officer on such an expedition.

----

V: hélas! vous n'avez pas éprouvé des infortunes telles que les miennes.
L: ho ve! vi ne spertis tiajn malfelicxojn, kiaj estis la miaj.
S: Aĥ! vi ne spertis tiajn malfeliĉojn, kiaj estis la miaj.

Formale tia "ho ve" esprimas la bedawron, ke "vi" ne spertis sufiĉe da
malfeliĉoj (kio evidente ne estas la intenco).

----

V: Ce /discours/ [28 vortoj] fit naître une /extrême/ curiosité dans
l'esprit de Cunégonde et de Candide. La vieille leur parla /en ces
termes/.

A: This speech raised a high curiosity in Candide and Cunegund; and
the old woman continued as follows.

A20: This speech having raised extreme curiosity in the *minds* of
/Cunégonde/ and Candide, the old woman spoke to them as follows.

L: Tia parolado [nur 27 vortoj!] naskis +tre+ grandan scivolon en la
spirito de Kunegond kaj de Kandid. La maljunulino parolis al ili jene.

S: Tiu respondo ekscitis grandan scivolon en Kunegundo kaj Kandido. La
maljunulino plu parolis jene:

----
ĉap. 11ª:
CHAPTER 11
The old woman'’s story

1. the daughter of Pope Urban X and the Princess of Palestrina: A non-existent Pope.
Voltaire had originally written ‘Clement XIT', an actual and recent Pope.
According to his secretary Wagniére, he intended to add the following
footnote, which appeared only in posthumous editions of Candide: ‘Note the
extreme discretion of our author at this point! Until now there has never
been a Pope Urban X. He is afraid to attribute a bastard daughter to an
existent Pope. What circumspection! What delicacy of conscience!"
Palestrina was an Italian principality, near Rome, which produced a Pope
named ... Urban VIII.

2. Massa-Carrara: A small Italian duchy, in Tuscany.

3. Gaeta: An Italian port, north of Naples.

4. Salé: A Moroccan port, near Rabat, and in the eighteenth century a notorious
centre of piracy targeted at Christian vessels. It is likewise a corsair from
Salé that swoops in Daniel Defoe’s (1660-1731) Robinson Crusoe (1719).

5. in articulo mortis: ‘At the point of death’. Only priests are authorized to give
absolution, but in their despair the soldiers have lost all sense of the
proprieties and are demanding Christian absolutions of a Muslim pirate.

6. Knights of Malta: An order of soldier-monks based in Malta, whose mission
was to defend Christian pilgrims against the infidel.

7. Muley Ismaél: Emperor of Morocco, who reigned ruthlessly for over fifty
years, and whose sons (two, not fifty) engaged in a protracted struggle for
power after his death in 1727.

----
ĉap. 13ª:

*** grandmanika --- un (!) cordelier à la grande manche 

"In 1581 the Franciscan order was riven by a dispute about the design
of its habit, in particular about the nature of its sleeves and the
hood. Hence the order was a favourite butt of Voltaire's anti-clerical
humour. Cordeliers are Franciscan friars, so called because they wear
a rope-belt. Since the Franciscan order began as a group of Mendicant
friars who set particular store by poverty, the use of the loose
sleeve in a manner akin to the poacher's procket has particular edge.


----
ĉap. 14ª:
Kurioze, la francigitan loknomon en <i lang="fr">le collège de
l’Assomption</i> (t.e. la Asunsjona kolegio) Lanti’ ne rekonis kaj
tradukis per «la kolegio de la Ĉieliro».



----
ĉap. 16ª:

We had now passed the mouth of the Aguarico, leaving behind us the
Christian Quitus and the peaceful Zaparos. Henceforth the right bank of the
Napo is inhabited by the Mazanes and Iquitos; while on the left are the wilder
Santa Marias, Anguteros, Oritos, and Orejones. The Orejones, or “Big Ears,”
enlarge those appendages to such an extent that they are said to lie down on
one ear and cover themselves with the other. This practice is now going out of
fashion. These Indians received their name, Orejones, or Oregones, from the
Spaniards, on account of this singular custom of inserting disks of wood in
the ears to enlarge them; the like practice prevailed among the tribes on the
Columbia River, Oregon. They trade in hammocks, poisons, and provisions.
The Anguteros, or Putumayos, have a bad reputation. They are reported to
have killed and robbed sarsaparilla traders coming up stream.

"The Andes and the Amazon" by James Orton
https://books.google.ru/books?id=Vr5cDwAAQBAJ&hl=ru&source=gbs_navlinks_s


The second utopia in this section is that of the Oreillons, who
existed in a pure state of nature, uncontaminated by manmade Western
civilization; Jesuit Paraguay was beyond the borders of their land.
All this relates to the concept of the noble savage, which became
increasingly popular in the latter half of the eighteenth century. The
idea was that nature itself was benign and good; let man live in a
state of pure nature and he in turn will be good. Pangloss had
embraced this philosophy of primitivism, as we learn from Candide. The
name Oreillons derives from the Spanish Orejones, which indicates
"pierced ears" or "big ears." Voltaire remained ironical in his
account of these utopians. Understandably, Candide began to question
all that had been taught him about "natural" man when it appeared that
Oreillons were going to boil or roast him, but once his life was
spared because he was not a Jesuit, he was no longer doubtful. The
obvious conclusion is that the primitive people are no better nor no
worse than so-called civilized people. Both are capable of great
cruelty.
https://www.cliffsnotes.com/literature/c/candide/summary-and-analysis/chapters-xiiixvi

----
ĉap. 18ª:

V: les grands officiers ... les menèrent à l'appartement de sa majesté
L: ... kondukis ilin en la apartamenton de Lia Reĝa Moŝto
S: ... kondukis ilin en la ĉambrojn de Lia Reĝa Moŝto
R: ... ввели их в покои его величества

PIV:
apartament³o. Loĝejo, konsistanta el pluraj ĉambroj, ordinare sur unu
sama etaĝo, interkomunikiĝantaj.

*apartments* [ plural ] mainly UK
a set of large rooms with expensive furniture and decoration in, for example, a public building or castle:
The Royal Apartments are open to the public.

Больше примеров
    They've got a fabulous apartment in the centre of Paris.
    She divides her time between her apartment in New York and her cottage in Yorkshire.
    I'll give you the keys to my apartment.
    They can presumably afford to buy a bigger apartment.
    They have six HOLIDAY APARTMENTS for sale.

ко́мната: ср.-в.-н. kem(e)n̄ate, ср.-нж.-нем. kemenade из лат. (camera) camīnāta "отапливаемая комната" от camīnus (см. ко́мин)

----
ĉap. 18ª:
caleçon → +kalsono+ → ŝorto

CALEÇON, subst. masc.
A. Vx. Culotte descendant sous le genou et portée autrefois par les
   personnes des deux sexes.

★kalson/o. *Subvesto* el diversaj formoj k ŝtofoj, kovranta parte aŭ
tute la femurojn, aŭ la tutajn gambojn. ☞ pantaloneto.

(Verdire, "ŝorto" estas pli mallonga; sed "kuloto" havas kromsencon
aristokratan, dum "ŝorto" konvenas al la klimato tropika.)

----
ĉap. 21ª:
<section id="n59"><title><p>[81]</p></title><p>Probable «Teorio de la Tero» de Bufono (1749) kun hipotezo eksplikanta la malkovron de maraj fosilioj sur montaj suproj. (Aŭ pli banale, <emphasis>Genezo</emphasis> 1:2.) — <emphasis>S.</emphasis></p></section>

terre ait été originairement une mer, comme on l'assure dans ce gros
livre qui appartient au capitaine du vaisseau[1]?

Either /Théorie de la Terre/ by Buffon (1749) or /l'Histoire des
navigations/ by Brosses (1756).

A reference to contempary scientific hypothesis that the mountains on
the earth were formed by an original sea. The proof for this was that
marine fossils had been found on the top of mountains.

----
ĉap. 22ª:
** habitué du quartier
A priest without a parish. Doesn't seem to have an equivalent in English...
http://www.cnrtl.fr/definition/habitu%C3%A9 :
spéc. 1477 part. passé subst. « ecclésiastique attaché au service
d'une paroisse sans y avoir charge ou dignité »
[en la postaj linioj "clerc"]

** konfesbileto
Un habitué du quartier vint avec douceur lui demander un billet
payable au porteur pour l'autre monde.

In the 18th century, last rites would often only be performed upon
presentation of a note from one's confessor (un billet de confession)
which confirmed that one had subscribed to a Papal Bull condeming
heretics.
http://www.britannica.com/EBchecked/topic/65386/billets-de-confession

The final episode in the controversy occurred from 1749 to 1754 over
the issue of /billets de confession/. The billets were papers
affirming submission to the bull that suspected Jansenists were
ordered to sign by the archbishop of Paris, Christophe de Beaumont. If
they refused, the last sacraments and burial in consecrated ground
would be denied them. The Parlement of Paris, claiming jurisdiction
over matters of ecclesiastical discipline and supported by public
opinion, opposed the billets. It ordered priests to administer the
sacraments to every one of the faithful under pain of banishment and
confiscation of goods. In 1754 King Louis XV forbade continuation of
the dispute.

** Le Fanatisme ou Mahomet le Prophète
«a pièce représente, sous le nom de Mahomet, le prieur des Jacobins
mettant le poignard à la main de Jacques Clément»
https://fr.wikipedia.org/wiki/Le_Fanatisme_ou_Mahomet_le_Proph%C3%A8te#Analyse

** toute seule de sa bande
V: elle fut enterrée toute seule de sa bande au coin de la rue de Bourgogne; 
de = "el" : "fare de";
*ARTIKOLO:* Kial "au coin"? ĉu sola angulo?

** tous les parolis, tous les sept-et-le-va de campagne
¹ /tous les parolis . . . campagne/: /parolis/ are double stakes whilst
/le sept et le va/ represents seven times the /vade/ or original stake. The
expression /de campagne/ means that the players who claimed these
gains were cheating.[fn:1]

² /dont ... cartes/: which they marked up for themselves by turning
down the corners of their cards.

³ /tailles/: hands or deals.

** toujours = ankoraŭ : ĉiam
V: Est-il vrai qu'on rit toujours à Paris?
L: Ĉu vere oni ankoraŭ ridas en Parizo?
S: Ĉu veras, ke la Parizanoj ĉiam ridas?

** la homo kun la ebura bastono
Laŭ L, «Policistoj Parizaj portas tian bastonon.» (neatribuita piednoto).
Dubinda aserto. La kunteksto:

V: Ah! monsieur, lui dit l'homme au bâton d'ivoire, eussiez-vous
commis tous les crimes imaginables, vous êtes le plus honnête homme du
monde …

A20: said the *understrapper of justice*, … (= subulo de justico)
P: rzekł *stróż bezpieczeństwa* …

Probable ironio pri «homo apartenabta al justico», ĉar «bâton d'ivoire»
estis simbolo de justico (kvankam ja REĜA simbolo de la REĜA justico):

LA MAIN DE JUSTICE

La main de Justice fut jusqu'en 1792 l'emblème du pouvoir judiciaire
des rois de France conféré par Dieu. Le roi est représenté par le
pouce, la raison par l'index, la charité par le majeur et la foi
catholique est symbolisée par l'annulaire et l'auriculaire.

C'est seulement à partir du XIIIe siècle que la main de Justice
s'imposa comme un symbole indissociable du pouvoir royal.

En 1226, à la mort de Louis VIII, sa veuve Blanche de Castille
s'empressa de faire sacrer son fils Louis IX (plus connu sous le nom
de Saint-Louis). Lors de son couronnement, il est remis au jeune roi
un BÂTON DE COMMANDEMENT décoré à son extrémité d'une MAIN EN IVOIRE
ayant trois doigts étendus.

L'emblème a ensuite perduré chez les descendants du souverain en
partie grâce à sa célèbre œuvre de Justice, rendue sous un chêne. La
main de Justice était conservée sous la royauté à l'Abbaye de
Saint-Denis.

 
QUE SIGNIFIE CE SYMBOLE ?

Lors de la cérémonie du sacre, on plaçait traditionnellement le
sceptre royal dans la main droite du souverain et la main de Justice
dans la gauche. Le symbole rappelle que le roi est la source de toute
Justice : à ce titre, il peut évoquer n'importe quel procès intenté à
l'intérieur de son royaume et prendre lui-même la décision qui sera
immédiatement exécutée sans discussion ni possibilité d'appel.

Cette charge de juge suprême a permis politiquement aux premiers
Capétiens d'asseoir la domination royale sur d'autres seigneurs
parfois plus puissants et de devenir véritablement les premiers
personnages du pays.

À l'aube de la Révolution, ce pouvoir fut de plus en plus discuté par
les Parlements (nom donné aux tribunaux à l'époque), notamment sous le
règne de Louis XV. Il fut ensuite placé au second plan par la
Constitution du 3 septembre 1791 pour être finalement supprimé
définitivement en même temps que tous les autres pouvoirs royaux le 10
août 1792.
[ https://www.justice.gouv.fr/histoire-et-patrimoine-10050/les-symboles-de-la-justice-21974.html ]

----
ĉap. 24ª:
(#aspekto; #artikolo; #cabinet:)
V: Paquette *ouvrait* ainsi son coeur au bon Candide,
dans /un cabinet/, en présence de Martin, qui *disait*
à Candide: …

Daŭra /ouvrait/, ripeta /disait/.
<!-- Kial "dans UN CABINET", la epizodo ja komenciĝas "dans la chambre
de Candide" "à son hôtellerie"??-->
A: in */his/ closet*.

S: Tiel parolis Violeto, malfermante sian koron al la bona Kandido;
kaj Marteno, kunestanta en la ĉambro, diradis al Kandido: …

Cetere, "malfermi sian koron" ne estas klara esprimo por "излить душу" ☹

----
ĉap. 26ª:

V: Sire, *la chaise* de votre majesté est à Padoue, et la barque est prête.
L: Reĝa Moŝto, +la portseĝo+ de via Majesto estas en Padova kaj la barko estas preta.
S: Via Majesto, *la kabrioleto* estas en Padovo kaj la barko pretas.

(La arkaika "chaise" efektive povas esti portseyo kaj vetuturilo;
ĉi-okaze temas pri veturilo, kiu atendas en la apuda urbeto Paduo,
kien el Venecio oni iros per barko.)

----
ĉap. 28ª:
V: ne savez-vous pas que le diable est toujours dans le corps de ces gens-là?
L: Ĉu do vi ne scias, ke la diablo ĉiam estas en la korpo de tiaj homoj?
S: Ĉu vi ne scias, ke en la korpo de tiaj homoj estas la diablo?

<p>Jen okazo kie V uzas pasivon pragmatike, L ĝin aktivigas kaj rezultas la bona vortordo Esperanta (ĉap. 29ª):
<cite>
- *V:* cette infamie ne me sera jamais reprochée
- *L:* tian malbonfamegon oni ne povos riproĉi al mi
- *S:* tian misfamegon mi ne allasos.
</cite>


* 7-Jara Milito: (1756—1763).

* Лейбниц

https://gallica.bnf.fr/ark:/12148/bpt6k4058995/texteBrut :
Quoi qu'il en soit, Leibniz déploie dans cette polémique une grande
érudition unie à une grande finesse on reconnaît à chaque page la
pénétration de son esprit et la souplesse de sa dialectique; mais l'on
y retrouve surtout la noblesse de ses sentiments et la bienveillante
générosité de son cœur; il ne parle de Bayle qu'avec une admiration
mêlée de respect et presque de tendresse, et, faisant allusion à sa
mort récente, il termine son Discours par ces touchantes paroles « Il
est à espérer que M. Bayle se trouve maintenant environné des lumières
qui nous manquent ici-bas, puisqu'il y, a lieu de supposer qu'il n'a
pas manqué de bonne volonté:

Candidus insueti miratur limen Olympi,
Sub pedibusque videt nubes et sidera Daphnis.
Светлый, дивится теперь вратам незнакомым Олимпа,
Ныне у ног своих зрит облака и созвездия Дафнис.
[Вергилий. Буколики V 56–57 (пер. С. Шервинского).]
(Citita de Lejbnico fine de "Предварительное рассуждение о согласии веры и разума")
(Radiant Daphnis is amazed at the unusual threshold of Olympus; he sees the clouds
and stars beneath his feet), Ecl. 5. 56-7; these lines are thought to be an imitation of De rerum
natura 5.1-54, where Lucretius calls Epicurus a god for having brought
humans a purged mind.

Blankega, nun miras ĉe l' sojlo Olimpa ... Dafniso

Таким образом, лучшее может быть превращено в другое, равноценное и
непревосходящее его; но между ними всегда будет существовать порядок,
и порядок наилучший из всех возможных. Если принимать всю
последовательность вещей, наилучшее не имеет себе равного, но часть
последствий может быть уравнена с другой частью той же самой
последовательности. Поэтому можно сказать, что вся последовательность
вещей, простирающаяся в бесконечность, может быть наилучшей из всех
возможных, хотя то, что существует во всем Универсуме в каждый
отдельный отрезок времени, не есть наилучшее. Итак, возможно, что
Универсум всегда переходит от лучшего к лучшему, если уж такова
природа вещей, что он не может достигнуть наилучшего сразу. Но о
подобных проблемах нам трудно судить. [Ч. 2, 202]

----------------

* Bildoj
** Bireto Jezuita
La plej klara: http://philippi-collection.blogspot.com/2013/09/jesuit-biretta.html

* Quarters of nobility
*Quarters of nobility* is an expression used in the bestowal of [[hereditary title]]s and refers to the number of generations in typically an [[ahnentafel]] in which noble status has been held by a family regardless of whether a title was actually in use by each person in the ancestral line in question.

For example, a person having sixteen quarterings (formally in [[heraldry]] [[Seize Quartiers]]) might have exclusively noble ancestry for the four previous generations (''i.e.'', to the great-great-grandparent level):  Given two parents per generation, four generations of uninterrupted nobility = 2⁴ = 16.  Alternatively, such a person might have exclusively noble ancestry for the five previous generations on one side but have a [[commoner]] for their other parent, such that the latter side of that person's ancestry would "dilute" by half the nobility they derived from the former side: (2⁵)/2 = 32/2 = 16.

Some [[orders of chivalry]] limit their membership to persons who can prove a certain number of quarterings (''e.g.'', sixteen for the [[Sovereign Military Order of Malta|Order of St. John]]).
https://en.wikipedia.org/wiki/Quarters_of_nobility

-------

Les *quartiers de noblesse* expriment, dans le système nobiliaire,
l'ancienneté des titres de noblesse d'une personne en fonction des
titres de noblesse de chacun de ses ascendants.

En pratique, le décompte des quartiers s'opère en cumulant, à chaque
génération, le nombre d'aïeux reconnus nobles. Deux grands-parents
nobles et trois arrière-grands-parents nobles donneront, par exemple,
cinq quartiers de noblesse. ------- Kaj la gepatroj ? 5+2=7 ?

En France, on compte par degrés et non par quartiers.

C'est à partir de la fin du Moyen Âge, en Europe centrale, qu'apparait
l'usage de définir la noblesse en faisant un décompte des « quartiers
de noblesse ». Plus précisément, ce serait les Allemands et les
Flamands qui auraient les premiers eu recours à un tel décompte, pour
répondre au problème posé par une éventuelle absence de noblesse du
côté des femmes.
https://fr.wikipedia.org/wiki/Quartiers_de_noblesse

----------------

*quartiers de noblesse* : Ensemble des ascendants nobles d'un
individu, pris à la même génération. (« Avoir quatre quartiers, huit
quartiers de noblesse », c'est avoir quatre, huit ascendants nobles
paternels et maternels.)

Il existe deux façons de compter l'ancienneté et donc la qualité de la
noblesse. Le premier, le compte par degré, consiste à remonter la
filiation masculine, de degré en degré, jusqu'à l'ancêtre premier. Le
second, le compte par quartier, prend en compte et la filiation
masculine et la filiation féminine.

Le premier système était utilisé en France. La noblesse n'étant
transmise que par l'homme, le mariage d'un noble avec une roturière
était facilité, celle-ci n'influant en rien sur la transmission de la
noblesse. L'inverse, naturellement, n'était pas vrai.

Le second système, celui de l'Europe centrale, tenait compte de la
qualité nobiliaire de la femme, au même titre que celle de l'homme. Il
n'est pas étonnant que l'usage s'en soit répandu en France au xviiie
s., période qui voit la noblesse se raidir sur ses privilèges et
exiger des preuves de noblesse particulièrement rigoureuses.


* Optimism
Leibniz’s purpose in his /Essais de Théodicée/ (1710: written in French) was essentially to
defend the rationality of God and His creation against an attack which, in his eyes, was a
potential danger to religion and to man’s confidence in the divine purposes. The French
Huguenot scholar and philosopher Pierre Bayle (1647-1706), a critical rather than a
constructive thinker, had frequently emphasized the limitations of the human reason by
drawing attention to philosophical paradoxes which appeared to admit of no rational
solution; and one of these, in his view, was the problem of evil. In the articles ‘Manichéens’
and ‘Pauliciens’ of his /Dictionnaire historique et critique/ (1697) he argued that the
explanation propounded by the ancient Manichean heresy, namely that the world was the
plaything of opposing gods, one good, one evil, was in fact the solution of the problem most
in keeping with the facts, however illogical and incompatible with our notions of God it
might be:
#+BEGIN_QUOTE
Qui n’admirera et qui ne déplorera la destinée de notre raison: voilà les Manichéens
qui avec une hypothèse tout-à-fait absurde et contradictoire expliquent les expériences
cent fois mieux que ne font les orthodoxes, avec la supposition si juste, si nécessaire, si
uniquement véritable d’un premier principe infiniment bon et tout-puissant
[‘Pauliciens,’ note E].
#+END_QUOTE
Leibniz’s book is a systematic discussion of Bayle’s views, and in it he propounds an answer
to the problem of evil which is in harmony with his own wider metaphysical thinking and
also supports the claims of rational theology. He sees God as subject, like man, to the laws
of reason: even God cannot make two and two add up to anything but four, nor create a
spherical cube. Hence, when God is considered as deciding upon the creation of the world,
Leibniz envisages him as having a choice only between possible worlds, that is, forms of
creation which do not violate the laws of reason, which do not involve logical contradiction.
And among such possible worlds God in His infinite goodness has inevitably chosen the
best. This ‘best of all possible worlds,’ however, necessarily contains imperfections, and
hence evil. While many evils are justifiable and even valuable as a means to good (e.g. the
protective and warning function of much physical pain), other evils are merely the inevitable
result of the imperfections inseparable from the status of created beings; man has limited
power, limited knowledge: ‘Il y a une imperfection originale dans la créature avant le péché,
parce que la créature est limitée essentiellement: d’où vient qu’elle ne saurait tout savoir, et
qu’elle se peut tromper et faire d’autres fautes’ (/Théodicée/, I, §20). Evil of this sort is thus
presented by Leibniz, not as a positive force, but rather as something negative and privative;
not anything willed by God, but an imperfection arising inevitably from the nature of things,
and to which man must consequently reconcile himself. The fact of evil is not denied, but its
presence in God’s creation is morally justified and rationally accounted for.

The second version of the philosophy of optimism is linked with the name of Alexander
Pope, not because he himself was an original thinker (he chiefly echoes the views of his
contemporary, Bolingbroke, and the earlier English philosopher, Shaftesbury), but because
he succeeded, in his /Essay on Man/ (1733), in crystallizing and giving memorable expression
to ideas on the subject which reflected the outlook of many contemporaries. It had become a
common practice for Christian apologists to invoke the new scientific discoveries as
evidence: that the marvels of the universe bear witness to God’s existence and His
providence is the theme of such works as the Rev. W. Detham’s /Physico-Theology/ (1713)
and /Astro-Theology/ (1715), both of which were frequently reprinted and translated into
French, and of the Abbé Pluche’s equally successful /Spectacle de la nature/ (1732). The
discovery of order and purpose in the world of nature led less orthodox thinkers, however, to
conclusions incompatible with the Christian doctrine of original sin. If scientific
investigation revealed the working of universal laws, the existence of rational purpose, in
every phenomenon so far scrutinized, it seemed likely that greater knowledge would display
the ultimate regularity and purposiveness of /everything/ in the universe: that whatever now
appeared as random, imperfect, evil, would be revealed as playing its necessary part in the
universal order. Man’s capacity for comprehending this order, it was argued, is inevitably
limited by his own quite restricted part in it, but the universe as a whole is perfect, the
unblemished product of the divine wisdom and omnipotence, and it is merely human
ignorance which makes us see imperfection and evil in it. Such are the views Pope advances
in the First Epistle of his /Essay on Man/:

#+BEGIN_VERSE
Cease then, nor order imperfection name:
Our proper bliss depends on what we blame.
Know thy own point: this kind, this due degree
Of blindness, weakness, Heav’n bestows on thee.
Submit. — In this or any other sphere,
Secure to be as blest as thou canst bear:
Safe in the hand of one disposing power,
Or in the natal, or the mortal hour.
All nature is but art, unknown to thee;
All chance, direction, which thou canst not see;
All discord, harmony not understood;
All partial evil, universal good;
And, spite of pride, in erring reason’s spite,
One truth is clear, Whatever is, is right.
#+END_VERSE

The distinction between this view and that of Leibniz is thus a wide
one. Leibniz, starting from a theological standpoint, admits the
reality of evil but sees it as an inevitable ingredient even in the
best of all possible worlds. Pope on the other hand, adopting an
approach which was of scientific inspiration, proclaims that evil is a
mere illusion, a consequence of human ignorance. And the moral which
the two writers drew from their conclusions similarly differed, for
while Leibniz wished by his vindication of the ways of God to men to
counteract the despair and helplessness which Manicheism might
provoke, and to encourage men to collaborate actively with God in the
working out of His purposes, Pope seems to preach only passive
submission to a Providence which, if universally rational and
ultimately beneficent, is also beyond man’s limited comprehension.

Such distinctions are important if we are to understand the history of
optimism, but in practice they were seldom made by the
eighteenth-century public. Pope’s poem was enormously successful in
France: no less than four different translations, two of which were
frequently reprinted, appeared between 1736 and 1750; and it was very
commonly, though erroneously, supposed that Pope had been influenced
by Leibniz. Interest in Leibniz, indeed, which had somewhat languished
in France since his death in 1716, was revived precisely by the
controversy which sprang up over Pope’s poem. It is significant that
the fullest discussion ever accorded to Leibniz’s /Théodicée/ in a
French periodical appeared, not in a review of the first edition of
1710, but in 1737, the year after the publication of the first French
translation of the /Essay on Man/, when the Jesuit /Mémoires de
Trévoux/ devoted four articles to reviewing an edition of the
/Théodicée/ published in 1734.

If Leibniz, who was little read, became better known, and by some
better thought of, as a result of this renewed French interest in
optimism, his reputation scarcely benefited in France from a further
development, which served nevertheless to keep his name before the
public in the following two decades. Owing chiefly to Leibniz’s
unwillingness to publish systematic expositions of his views, his
philosophy, for all its originality and importance, exercised
extremely little direct influence: but early in the eighteenth century
there appeared in Germany an academic disciple of Leibniz whose impact
was considerable. Christian Wolff (1679-1754), a professor in the
universities of Halle and Marburg, was above all a systematizer and an
expositor, developing some of Leibniz’s principal conceptions into an
all-embracing philosophical structure which covered every aspect of
human thought, from logic to theology, from metaphysics to ethics.
This he presented in lectures to students over a period of thirty
years and published in some forty quarto volumes, in which his thought
is set out in a rigidly organized pattern resembling that of a
textbook of geometry. The apparently solid, ‘mathematically’ proven
certainties of this arid and pedantic philosophical system had great
appeal for his contemporaries, however, and before his death Wolff’s
philosophy had become the established orthodoxy in the universities of
northern Germany.

The issue at stake in the controversy was a crucial one. The optimism
expressed in Pope’s poem, and which was commonly supposed to be that
of Leibniz also, appeared in the 1730s as a characteristically deistic
view. It presented God as a rational Supreme Being, the creator of a
rational, ordered, perfect universe; it clearly left no room for such
notions as the Fall, original sin, Christ’s atonement, redemption by
divine grace, or even, in the eyes of many, for freedom of the will.
And at that date deism was the commonest form assumed by the growing
European movement of free thought, the strongest enemy with which the
Church had to contend. The forces of orthodoxy consequently reacted
vigorously, condemning such doctrines as unchristian and above all
fatalistic; but their attraction remained strong in an age which
tended to complacency, was impressed by the achievements of the new
science, and found the rationalistic notions of deism more congenial
than the dogmas of revealed religion.

It was in these Protestant areas of the country that many thousands of
Huguenots had settled when in 1685 the revocation of the Edict of
Nantes had forced them to leave France. These refugees, and especially
the second generation, born in exile, while they preserved their
religious traditions and their national language, also came inevitably
under the influence of contemporary German movements. Some became
enthusiastic Wolffians, and consequently tried to win further
adherents by spreading knowledge of Wolff’s system in the
French-speaking world. French translations and expositions of Wolff
were published in the late 1730s and the 1740s by Jean Deschamps, a
little-known pastor in Berlin who later lived in London, and by the
much more influential J.H.S. Formey, a Huguenot minister and professor
who became the permanent Secretary of the Berlin Academy of Sciences
in 1748, contributed articles to Diderot’s /Encyclopédie/, and was
extremely active throughout his career as a publicist and journalist.
Formey’s most ambitious attempt at presenting Wolff to French readers
was /La Belle Wolfienne/ (6 vols., 1741-53), a work which, in the
early volumes at any rate, tried to emulate the conversational method
of popular scientific exposition used so successfully by Fontenelle in
his /Entretiens sur la pluralité des mondes habités/ half a century
before. But certainly more influential than this was his journalistic
work. From 1734 until its disappearance in 1760 Formey was on the
editorial staff of a periodical primarily concemed with presenting
German literary and intellectual life to French readers, the
/Bibliothèque germanique/, and in the 1740s and ’50s he was able to
use it as an organ of Wolffian propaganda, consistently publishing
articles and reviews in which Wolff’s philosophy was expounded and put
forward in a favourable light.

The positive effect of this campaign in France itself was not very
great. The only French convert to Wolffianism of any significance was
Voltaire’s mistress, Madame Du Chatelet. Won over, at least
temporarily, by the enthusiasm of a disciple of Wolff whom she
employed for a time as a mathematics tutor, Samuel König, she prefaced
a popular introduction to physics which she published in 1741, the
/Institutions de physique/, with an outline of the metaphysical
conceptions of Leibniz (including the doctrines of the /Théodicée/),
‘puisées dans les ouvrages du célébre Wolff.’ The general effect,
however, of such pro-Wolffian activities was at least to keep the
names of Leibniz and Wolff before the French public by provoking
opposition. Apart from Madame Du Chatelet’s book, during the twenty
years preceding /Candide/ virtually nothing was published on the
subject in France itself which was not hostile to the Wolffian
philosophy. It appeared to most French minds as an extreme example of
a kind of dogmatic speculation which the new scientific progress,
based upon observed fact only, had shown to be valueless. Condillac
dealt this sort of philosophy a crushing blow with his devastatingly
critical /Traité des systémes/ in 1749, and D’Alembert in 1751
recorded the decease of systematic metaphysics in his /Discours
préliminaire de l'Encyclopédie/: ‘Le goût des systémes, plus propre a
flatter imagination qu’a éclairer la raison, est aujourd’hui
presqu’absolument banni des bons ouvrages.”

The interest in the doctrines of optimism which Pope’s /Essay on Man/
had stimulated in France was thus reinforced to some extent by the
attempts of Madame Du Châtelet and the Huguenot enthusiasts in Germany
to attract French support for the philosophy of Leibniz and Wolff.
Pope and Leibniz were continually linked together by
controversialists, ‘le meilleur des mondes possibles’ and Pope’s ‘tout
est bien’ (‘Whatever is, is right’) became the catch-phrases of the
discussion: but even those in France who sympathized with the
optimistic solution of the problem of evil were rarely disposed to
accept also the complete metaphysical system in which Wolff had
embedded it. The outlines of that system became better known in France
than Leibniz’s own thought had ever been, thanks to the efforts of the
Wolffian propagandists: but Frenchmen, it seems, if they were able now
to recognize such technical phrases as ‘l’harmonie préétablie,’ ‘la
raison suffisante,’ or ‘les monades’ as characteristically Leibnizian,
saw no reason to take Leibnizian metaphysics seriously, and now also
associated it with the pedantic aridity and prolixity of Wolff—who in
these respects well exemplified the current French conception of
German pedagogues and scholars.

Optimism itself, moreover, though defended by enthusiasts in Germany,
continued to come under fire in France. As we have seen, the forces of
religious orthodoxy condemned it, emphasizing especially the
fatalistic implications which were inseparable from it; and to many
men of sense it seemed less and less in accordance with the observable
facts of existence—an impression which was of course enormously
strengthened by the Lisbon earthquake of 1755.

We are now in a better position to understand the immediate success of
/Candide/. In it Voltaire is making fun of a philosophy much discussed
in France, but generally rejected there: one which aroused great
interest, because it was concerned with a problem of acute importance
for the age, but which had also acquired an aura of ridicule through
becoming associated in the public mind with the academic jargon of
German pedants and their infatuated disciples. In creating Pangloss,
the German pedagogue, with his Leibnizian clichés, his irrepressible
passion for metaphysical dogmatizing, and his blind devotion to
optimism, Voltaire was setting up a butt for satire at which all
France could laugh.

-----

To describe the development of Voltaire’s attitude to the question of optimism it is not
necessary, or possible, to go back to the earliest years of his career: the successful young
court poet and dramatist of the Regency had as yet no serious personal concern with such
profound matters as the problem of evil. Yet, with his early interest in Bayle and impatience
with religious orthodoxy, he can scarcely have failed, even as a very young man, to be aware
of the importance of the question. He of course read his friend Pope’s /Essay on Man/ as soon
as it appeared in 1733, and it is noteworthy that, although he qualified his first praise of it
with the remark that ‘Now and then there is some obscurity’ (letter, in English, to Thieriot,
24 July 1733, Best. 614), his own earliest recorded opinions on the subject, which belong to
...................

W.H. BARBER: [The Question of Optimism]+
+ Originally published in French, “Sur le style philosophique de Candide,”
  in Comparative Literature 28 (1976), pp. 193—200, This
  translation, by Nicholas Cronk, is based on the slightly revised
  version that appeared in /Le Reméde dans le mal/ (Paris: Gallimard,
  1989), pp. 123-44, © Editions Gallimard, Paris, 1983, 1989.    
 
Candide (Third International Edition)
Voltaire
W. W. Norton & Company, 15 апр. 2016 г.
ISBN	0393617483, 9780393617481

Candide has been delighting readers since 1759 with its satiric wit, provocations, and warnings.
The novella has never been out of print and has been translated into every conceivable language. The text of this Norton Critical Edition remains that of Robert M. Adams’s superlative translation, accompanied by explanatory annotations.

The Norton Critical Edition also includes:
· A full introduction by Nicholas Cronk.
· Six background studies of Enlightenment ideas and themes (by Richard Holmes, Adam Gopnik, W. H. Barber, Dennis Fletcher, Haydn Mason, and Nicholas Cronk), five of these new to the Third Edition.
· Seven critical essays—five of them new to this edition—representing a wide range of approaches to Candide. Contributors include J. G. Weightman, Robin Howells, James J. Lynch, Philip Stewart, Erich Auerbach, and Jean Starobinski.
· A revised and expanded Selected Bibliography.
https://books.google.ru/books?id=oiFjDAAAQBAJ&pg=PT158&lpg=PT158&dq=Quarters+of+nobility+Candide+Cunegunde+Voltaire&source=bl&ots=EPaLKDM5Mj&sig=ACfU3U2Fme9wXwrO8K6As4Ti_GMpyzh68w&hl=ru&sa=X&ved=2ahUKEwir76Hoo4H5AhUzQfEDHdNwBxoQ6AF6BAgqEAM#v=onepage&q=Quarters%20of%20nobility%20Candide%20Cunegunde%20Voltaire&f=false
 


<h4 id="Ij">Interjekcioj</h4>
Hélas: 15
Ah: 16





* Footnotes

[fn:1] Littré: « *campagne:* 6° Terme de jeu. À la bassette et au
Pharaon, paroli de campagne, paroli marqué par tricherie ; au
trictrac, case de campagne, case qu'on n'avait pas le droit de faire.»
